const PREFIX = 'Scrumpoker';

export const LOADING = `${PREFIX}/LOADING`;
export const BOOTSTRAP_DONE = `${PREFIX}/BOOTSTRAP_DONE`;
export const SET_STORIES_LIST = `${PREFIX}/SET_STORIES_LIST`;
export const SET_USERS_LIST = `${PREFIX}/SET_USERS_LIST`;
export const SET_VOTES_LIST = `${PREFIX}/SET_VOTES_LIST`;
export const SET_CURRENT_USER = `${PREFIX}/SET_CURRENT_USER`;
export const SET_VOTING_ENDED = `${PREFIX}/SET_VOTING_ENDED`;
export const RESET_APP = `${PREFIX}/RESET_APP`;
