const PREFIX = 'App';

export const LOADING = `${PREFIX}/LOADING`;
export const BOOTSTRAP_DONE = `${PREFIX}/BOOTSTRAP_DONE`;
export const SET_STORIES_LIST = `${PREFIX}/SET_STORIES_LIST`;
export const SET_USERS_LIST = `${PREFIX}/SET_USERS_LIST`;
export const SET_VOTES_LIST = `${PREFIX}/SET_VOTES_LIST`;
export const SET_USER_VOTE = `${PREFIX}/SET_USER_VOTE`;
export const SET_CURRENT_USER = `${PREFIX}/SET_CURRENT_USER`;
export const SET_VOTING_ENDED = `${PREFIX}/SET_VOTING_ENDED`;
export const SET_SUMMARY = `${PREFIX}/SET_SUMMARY`;
export const RESET_APP = `${PREFIX}/RESET_APP`;

export const GET_JIRA_EPICS = `${PREFIX}/GET_JIRA_EPICS`;
